export enum PlantType {
  ROSE = "ROSE",
  GERBERA = "GERBERA",
  CACTUS = "CACTUS",
  DIEFFENCBACHIA = "DIEFFENCBACHIA",
  ASPARAGUS = "ASPARAGUS",
  ORCHIDACEAE = "ORCHIDACEAE",
  BONSAI = "BONSAI",
}
