export enum PlantType {
  CRASSULA_OVATA = "CRASSULA_OVATA",
  DAISY = "DAISY",
  GERBERA = "GERBERA",
  GUZMANIA = "GUZMANIA",
  LILIUM = "LILIUM",
  OLIVE = "OLIVE",
  ORCHID = "ORCHID",
  ROSE = "ROSE",
  SPATIFILYUM = "SPATIFILYUM",
  SUCCULENT = "SUCCULENT",
}
